gatling {
  core {
    outputDirectoryBaseName = ""
    runDescription = ""
    encoding = "utf-8"
    simulationClass = ""
    elFileBodiesCacheMaxCapacity = 200
    rawFileBodiesCacheMaxCapacity = 200
    rawFileBodiesInMemoryMaxSize = 1048576
    pebbleFileBodiesCacheMaxCapacity = 200
    shutdownHook = true
    extract {
      regex {
        cacheMaxCapacity = 200
      }
      xpath {
        cacheMaxCapacity = 200
      }
      jsonPath {
        cacheMaxCapacity = 200
      }
      css {
        cacheMaxCapacity = 200
      }
    }
    directory {
      simulations = user-files/simulations
      resources = user-files/resources
      results = /app/results
    }
  }
  charting {
    noReports = false
    maxPlotsPerSeries = 1000
    useGroupMarkers = false
  }
  http {
    fetchedUserCacheMaxCapacity = 200
    warmedUp {
      enabled = true
      url = "https://gatling.io"
    }
    request {
      maxRedirects = 20
    }
  }
}
